announce = false
debug = true
description = 'Omega RolePlay Server'
gamemode = 'roleplay'
host = '127.0.0.1'
language = 'en'
modules = [ 'js-module' ]
name = 'Omega RolePlay Server'
players = 10
port = 7788
resources = [
    'chat',
    'roleplay',
    'BetterNoClip',
    'speedo',
    'altV-Extended',
    'voice-chat',
    'O_functions',
    'altmp-js-network-streamer',
    'etron',
    'mustang',
    'mclaren',
    'ocni422spe'
]
voice = true
website = 'example.com'